
% \VignetteIndexEntry{Kirkpatrick et. al (2016) data analysis}
% \VignetteEngine{knitr::knitr}

\documentclass{article}

\input{Shared_Preamble.tex}

\def\githubLoc/{https://github.com/dpritchLibre/PRISMS}




% Document start ---------------------------------------------------------------

\begin{document}

% Configure global options
<<setup, cache=FALSE, include=FALSE>>=
library(knitr)
knit_theme$set("default")
opts_chunk$set(cache=FALSE)
opts_knit$set(root.dir=normalizePath(".."))
options(width=90)
@


\begin{center}
  \Large
  Data analysis performed in the paper: \\[1ex]
  \papernamefull/
  \vspace{10mm}

  {\large \today}

\end{center}
\vspace{10mm}

\tableofcontents
\vspace{10mm}




% Begin document body ----------------------------------------------------------

\setcounter{section}{-1}
\section{Introduction}

The \pkg{PRISMS} \R/ package provides a collection of software tools used to
facilitate the prioritization of putative bioactive compounds from a complex
biological matrix.  The package was constructed to provide an implementation of
the statistical portion of the laboratory and statistical procedure proposed in
\papernamefull/ (herafter abbreviated to \papername/) \cite{kirkpatrick2016}.

This document describes all of the steps and shows the results of the data
analysis performed in \papername/.  Providing the analysis will hopefully make
the research more reproducible, give the interested reader a greater
understanding of the methodology developed in the paper, and to provide a
working template for researchers who may wish to apply the methodology developed
in the paper to their own research problems.


\section{Data collection}

This section describes in brief the data collection procedures that are
performed upstream of the data analysis.  Please refer to \papername/ for far
more detail regarding this process. \vspace{-2mm}


\subsection{\textit{Viola odorata} sample preparation and LC-MS/MS
  analysis} \label{sec: lcms}

Aqueous extraction of \textit{Viola odorata} aerial tissue was performed to
selectively extract for AMP-like compounds.  The resulting extract was crudely
fractionated using strong cation exchange (SCX) chromatgraphy for creation of the
\textit{Viola odorata} peptide library.  Bioactivity assays against a panel of
microbial pathogens were performed using the generated peptide library.  Each
SCX fraction was then subject to nano-LC-ESI-MS/MS (a Waters nanoAcquity UPLC
coupled to an AB Sciex TripleTOF5600).  After processing of this
dataset, accurate intact mass and relative intensity information for peptide
constituents contained within each fraction was obtained, resulting in 30,799 MS
features for \textit{Viola odorata} across the 34 fractions.


\subsection{Bioactivity screening} \label{sec: bioact}

Peptide libraries were assayed for growth inhibition against the following
pathogens: E. coli (ec), S. aureus (sa), K. pneumoniae (kp), A. baumannii (ab), P. aeruginosa (pa),
E. cloacae (ec), F. graminearum (fg) and cancer cell lines: breast cancer (bc), prostate cancer (pc) and ovarian cancer (oc). Library fractions are incubated with a microbial or cancer cell
culture and the presence of bioactive peptides in a given fraction will result
in inhibition of culture growth during the incubation period.  For bacterial
assays, the remaining viable cells are quantified indirectly by
spectrophotometric measurement of the irreversible intracellular reduction of
resazurin25.  For anticancer bioactivity, cytotoxicity assays are performed
using MTT-based assays to measure mitochondrial succinate dehydrogenase activity
with absorbance measurements at 570 nm. Values for each fraction are compared to
positive and negative controls containing a known therapeutic or water,
respectively, to determine a percent activity of each library fraction, where a
small value of remaining viable cells indicates high activity.  Percent activity
of each well was calculated using the formula:
\[ \text{percent activity} = 100 \times \frac{ \text{RFU of fraction} -
    \text{RFU of positive control} }{ \text{RFU of negative control} -
    \text{RFU of positive control} }
\]
where RFU stands for \textit{relative fluorescence units}.




% Paper data analysis ----------------------------------------------------------

\section{Data analysis presented in \papername/} \label{sec:
  prototypical}

This section describes all of the steps and shows the results of the data
analyses performed in \papername/, which is the workflow shown in Figure
\ref{fig: flow chart prototypical}.  In this scenario, mass spectrometry
abundance values for each compound across the SCX fractions is obtained
using LC-MS/MS analysis as described in section \ref{sec: lcms}, and is
represented by the pink oval.  The mass spectrometry data is consolidated via
the \binMS/ function, and the resulting consolidated data is filtered by the
\filterMS/ function.

Bioactivity data is collected as described in section \ref{sec: bioact}, and is
represented by the green oval. The bioactivity data is then then provided along
with the consolidated and filtered data as inputs to the \rankEN/ function,
which calculates and returns the data analysis results.


\begin{figure}[H]
\caption{Data analysis flow chart for the data analysis performed in \papername/}

\centering
\begin{tikzpicture}[node distance = 3cm, auto]
    % Place nodes
    \node [decision] (rankEN) {rankEN};
    \node [block, left of=rankEN] (filterMS) {filterMS};

    \node [cloudYel, right of=rankEN, node distance=3.75cm] (ranked_data)
    {\makecell[c]{ranked candid-\\ate compounds}};

    \node [block, left of=filterMS] (binMS) {binMS};
    \node [cloud, left of=binMS] (raw_data) {\makecell[c]{raw MS\\data}};
    \node [cloudGr, below of=rankEN] (bioact) {\makecell[c]{bioactivity\\data}};
    % Draw edges
    \path [line, thick] (raw_data) -- (binMS);
    \path [line, thick] (binMS) -- (filterMS);
    \path [line, thick] (filterMS) -- (rankEN);
    \path [line, thick] (rankEN) -- (ranked_data);
    \path [line, thick] (bioact) -- (rankEN);
\end{tikzpicture}

\label{fig: flow chart prototypical}
\end{figure}



\subsection{Loading the mass spectrometry and bioactivity data}

First, we load the mass spectrometry data collected for \papername/.  The raw
data produced by this system is stored as a comma-seperated values file.
However, in an effort to minimize the size of the \pkg{PRISMS} package, we have
removed the columns in the data corresponding to variables not used in the data
analysis, and have converted the data to a compressed native \R/ format.  The
values of the data relevent to this data analysis of course remain unchanged
from their original form.

Readers who wish to obtain the data in its raw form may obtain the data as well
as the \R/ script used to convert the raw data into the form provided with the
package from the \pkg{PRISMS} package developement repository located at
\url{\githubLoc/}.


\subsubsection{Mass spectrometry data}

The mass spectrometry data yielded intact mass and relative intensity
information for peptide constituents contained within each library fraction; the
analysis obtained 30,799 MS features for \textit{Viola odorata} across fractions
1-43.


<<reading-data-ms>>=
library(PRISMS)

# Load mass spectrometry data into memory
data(mass_spec)
@



\subsubsection{Bioactivity data}

Peptide libraries were assayed for growth inhibition against the following
pathogens: E. coli (ec), S. aureus (sa), K. pneumoniae (kp), A. baumannii (ab), P. aeruginosa (pa),
E. cloacae (ec), F. graminearum (fg) and cancer cell lines: breast cancer (bc), prostate cancer (pc) and ovarian cancer (oc).  Three replicate observations were collected for each of the
assays (with the exception of fg, which had two
replicates), across fractions 1-43.  The resulting percent activity of each fraction was quantified using cell viability assays, and the average response across all replicates was used for this analysis. 

<<reading-data-bioact>>=
# Load bioactivity data into memory
data(bioact)
@




\subsection{Consolidating mass spectrometry data}

Now that we have the mass spectrometry data loaded into memory, the first step
in the \pkg{PRISMS} pipeline is to to consolidate mass spectrometry observations
in the data that are believed to belong to the same underlying compounds.  In
this way, all of the abundance belonging to the same compound will be aggregated
together and thus resemble a more accurate depiction of the compound abundance
accross SCX fractions. This is performed via the \binMS/ function.

% In order to perform its task, the consolidation routine needs to be provided
% with data for each mass-to-charge and charge state, the time of peak retention,
% and optionally the mass.  These can be provided as data vectors, or can be given
% as columns in the mass spectrometry data.  When provided as part of the mass
% spectrometry data, these variables can each be identified either by column
% index, or by column name.  In this case the values for these variables are
% included in the \texttt{mass\_spec} data, and we will specify them by (partial)
% names.

% The mass spectrometry intensities need to be included as part of the data
% provided as the argument to \texttt{mass\_spec}.  As other types of data are
% allowed to be included as part of this object, we need to specify which columns
% in the data correspond to the intensities.  If all of the columns correspond to
% intensities, then we specify \texttt{NULL}.  Otherwise, we can specify a vector
% either of column indices, or of column names.  In this example we will take the
% easy way out and specify the column indices.

% As part of the procedure, we also need to specify acceptable values for the time
% of peak retention, an allowable mass range, an allowable charge state range.
% These are provided as length-2 vectors specifying the lower and upper bounds of
% the acceptable ranges.

% Finally, we need to specify the closeness of mass-to-charge values and times of
% peak retention for observations which we presume as having come from the same
% underlying compounds.  This is done by specifying a cutoff value for which
% differences larger than these values will be considered as coming from two
% distinct mass-to-charge levels.


\subsubsection{Specification of criteria} \label{sec:ms_criteria}

The binMS function contains many criteria to help filter out unwanted compounds
and thereby focusing the list on potential compounds of interest. Retention time
limitations are in place to eliminate background ions that are detected before
(equilibration) or after (wash) the gradient is applied. For our gradeint, 14 and 45 minutes were appropriate retention time filters. Mass and charge
limitations of 2 to 15 kDa and +2 to +10, respectively, restrict compounds to
the mass and charge ranges of known bioactive peptides. A m/z difference of 0.05
Da was chosen based off of test data sets in which fluctions in mass accuracy
and retention time allowed the same peak to be picked multiple times despite
representing the same compound. A retention time difference can also be
specified to facilitate the aforementioned process. A rentetion time equal to
the run time can be used to specify that all compounds of the same mass within
the m/z difference should be consideree the same feature, as was performed in this analysis.




\subsubsection{Consolidating data with \texttt{binMS}}

Here we perform the mass spectrometry consolidation prodedure, using the
criteria as described in \ref{sec:ms_criteria}.  We can see from the summary
output that the number of of candidate compounds has been reduced from an
initial amount of 30,799 observations to 6,258 compounds.

The reduction of candidate compounds can be further broken down into two steps.
The first is an exclusion process, and we can see that the number of elution
levels that satisfied the criterion for time of peak retention, mass, and charge
level were 26,387, 11,482, and 19,250 levels, respectively.  The number of
elution levels that satisfied all of the inclusion criteria was 10,902.  Then
the consolidation step consolidated those 10,902 elution levels into 6,258
candidate compounds.

<<consolidating-data>>=

# Perform mass spectrometry levels consolidation
bin_out <- binMS(mass_spec = mass_spec,
                 mtoz = "m/z",
                 charge = "Charge",
                 mass = "Mass",
                 time_peak_reten = "Reten",
                 ms_inten = NULL,
                 time_range = c(14, 45),
                 mass_range = c(2000, 15000),
                 charge_range = c(2, 10),
                 mtoz_diff = 0.05,
                 time_diff = 60)

# Show some summary information describing the consolidation process
summary(bin_out)
@

\subsection{Filtering mass spectrometry data}

The next step in the \pkg{PRISMS} pipeline is to remove any potential candidate
compounds with observed abundances for which it is not scientifically plausible
that they might be a compound with an effect on bioactivity levels.  This step
is performed by the \texttt{filterMS} function.




\subsubsection{Selecting fraction region of interest(s)}

Bioactivity regions of interest are selected based on each individual
bioactivity data set. Based on the SCX peak width, a given peptide should elute
over a minimum of three fractions in a Gaussian manner. Beacuse mass
spectrometry is more sensitive than the bioactivity assays, the defined
bioactivity region can extend 1-2 fractions beyond the visibile activity range
on either end. The defined bioactivity regions for each species deemed active
are depicted by blue bars in figure \ref{fig:fracs-of-interest}.

\begin{figure}[p]
  \centering
  \includegraphics[width=0.80\textwidth]{images/Analysis_Regions}
  \caption{Percent decrease in bioactivity levels, averaged over replicates.
    The fractions selected as the region of interest are shown in blue.}
  \label{fig:fracs-of-interest}
\end{figure}



\subsubsection{Filtering criteria selection}

Similar to the filtering criteria for the \binMS/ function, the main purpose of
this function is to eliminate noise and focus only on those compounds possibly
contributing to activity. To do this, we specify that a compound must have its
maximum intensity inside the defined bioactivity region. Additionally, that
compound cannot be more abundant than 0.01 * it's maximum abundance outside the
bioactivity region. This value accounts for small fluctation from absolute 0
that are most likely due to noise, and was defined through our test data sets. A minimum intensity value of 1000 is applied folowing
the same logic and can be adjusted to reflect the appropriate noise level of
each instrument. The resulting list of candidate compounds remaining after the
\filterMS/ list are all compounds that logically could be contributing to the
activity.



\subsubsection{Filtering data with \texttt{filterMS}}

Here we perform the filtering operation to remove any potential candidate
compounds with observed abundances for which it is not scientifically plausible
that they might be a compound with an effect on bioactivity level using the
\filterMS/ function.  We can see that 3,428 compounds satisfied criterion 1,
3,428 compounds satisfied criterion 2, 3,428 compounds satisfied criterion 3,
3,428 compounds satisfied criterion 4, and 3,428 compounds satisfied criterion
5.  In total, 225 compounds satisfied each each of the 5 criteria.

<<filtering-data>>=
# Perform mass spectrometry levels filtering
filter_out <- filterMS(msObj = bin_out,
                       region = paste0("VO_", 17:25),
                       border = "all",
                       bord_ratio = 0.01,
                       min_inten = 1000,
                       max_chg = 10)

# Show summary information describing the filtering process
summary(filter_out)
@


\subsection{Candidate compound ranking} \label{sec:ranking}

In this section potential candidate compounds are ranked in order to facilitate
the investigation of compounds with a negative effect on each of the bioactivity
peptide libraries, using the \rankEN/ function.  For each library the mass
spectrometry data remains the same.  Also note that the region of interest
changes over the peptitde libraries, according to the selections shown in figure
\ref{fig:fracs-of-interest}.

<<candidate-compound-ranking>>=

# Rank the candidate compounds using the ranking procedure for each of the
# bioactivity datasets
rank_oc <- rankEN(msObj      = filter_out,
                  bioact     = bioact$oc,
                  region_ms  = paste0("VO_", 18:22),
                  region_bio = paste0("VO_", 18:22),
                  lambda     = 0.001)
rank_bc <- rankEN(msObj      = filter_out,
                  bioact     = bioact$bc,
                  region_ms  = paste0("VO_", 18:23),
                  region_bio = paste0("VO_", 18:23),
                  lambda     = 0.001)
rank_pc <- rankEN(msObj      = filter_out,
                  bioact     = bioact$pc,
                  region_ms  = paste0("VO_", 17:21),
                  region_bio = paste0("VO_", 17:21),
                  lambda     = 0.001)
rank_ab <- rankEN(msObj      = filter_out,
                  bioact     = bioact$ab,
                  region_ms  = paste0("VO_", 17:21),
                  region_bio = paste0("VO_", 17:21),
                  lambda     = 0.001)
rank_ef <- rankEN(msObj      = filter_out,
                  bioact     = bioact$ef,
                  region_ms  = paste0("VO_", 18:21),
                  region_bio = paste0("VO_", 18:21),
                  lambda     = 0.001)
rank_pa <- rankEN(msObj      = filter_out,
                  bioact     = bioact$pa,
                  region_ms  = paste0("VO_", 18:25),
                  region_bio = paste0("VO_", 18:25),
                  lambda     = 0.001)
rank_ec <- rankEN(msObj      = filter_out,
                  bioact     = bioact$ec,
                  region_ms  = paste0("VO_", 18:22),
                  region_bio = paste0("VO_", 18:22),
                  lambda     = 0.001)
rank_fg <- rankEN(msObj      = filter_out,
                  bioact     = bioact$fg,
                  region_ms  = paste0("VO_", 19:24),
                  region_bio = paste0("VO_", 19:24),
                  lambda     = 0.001)

@




% Candidate compound ranking ---------------------------------------------------

\section{Proof-of-method via the cyO2 compound}

To validate this pipelne, we demonstrate successful detection and identification of a known AMP 
from the botanical species Viola odorata. Viola odorata, commonly known as sweet violet, contains 
many cyclotides - including cycloviolacin O2 (cyO2). CyO2 is a small, cysteine rich cyclotide 
comprised of 30 amino acids (MWmonoisotopic: 3138.37 Da), which has been shown to have diverse 
activity against many Gram-negative bacteria (E. coli, K. pneumoniae, and P. aeruginosa), as well
as several cancer cell.  Here, we demonstrate successful detection and identifiaction of cyO2 thereby
validating the use of this statistical analysis approach for bioactive peptide discovery.




\subsection{cyO2 compound ranking results}

Each of the \R/ objects created in section \ref{sec:ranking} contains a ranking
of the candidate compound obtained using the procedure.  The ranked compounds'
m/z values is provided in the \texttt{mtoz} element of the \texttt{rankEN}
object, while the ranked compounds' corresponding charge values are found in the
\texttt{charge} element.

The exact m/z and charge values for cyO2 were obtained by comparing the
candidate compounds list after the consolidation and filtering process to the
known range of values; the m/z and charge pairs were determined to be
approximately (1047.4898, 3), and (1570.2414, 2).  Thus the \R/ function
\texttt{find\_cyO2\_rank} returns a vector of the rankings of these two
incarnations of cyO2.

From the output we see that for ef, pc, and bc, at least one charge state corresponding
to cyO2 is identified in the first 10 candidate compounds.  CyO2 is identified as the 23rd
and 33rd compounds for ab and pa, respectively, and for the remaining bioactive
peptide libraries cyO2 is ranked within the top 100 compounds. 

<<cyO2-rankings>>=
# Function to find the rank of cyO2 compounds
find_cyO2_rank <- function(rankEN_obj) {
    # The m/z values for the two incarnations of cyO2
    mval1 <- 1047.4897758000001886
    mval2 <- 1570.2413587500000176
    # Find the indices (corresponding to the ranks) of the cyO2 incarnations
          which((rankEN_obj$mtoz == mval1 & rankEN_obj$charge == 3) |
                (rankEN_obj$mtoz == mval2 & rankEN_obj$charge == 2))
}

# List the ranks for cyO2
lapply(list(ab=rank_ab, bc=rank_bc, ec=rank_ec, ef=rank_ef,
            fg=rank_fg, oc=rank_oc, pa=rank_pa, pc=rank_pc),
       find_cyO2_rank)
@




% bibliography -----------------------------------------------------------------

\begin{thebibliography}{9}

\bibitem{kirkpatrick2016} Kirkpatrick et al.  A PRISMS pipeline for natural
  product bioactive peptide discovery.

\end{thebibliography}


\end{document}


\end{document}
